### ISSUE TITLE
spm_get error when trying to fix "Cant open image file"

### ISSUE THREAD

**Issue by TamerGezici** [marsbar-toolbox/marsbar#7]
Hi,

I am trying to do ROI analysis using Marsbar, and I did the necessary changes to my script to fix the Can't open image file error.

My matlab script is here:

https://gist.github.com/TamerGezici/f1209b9b9fade29d6ded6dec9dcf72a9

However, I ran into an error on this line which says spm_get is not a function that exists.

https://github.com/marsbar-oolbox/marsbar/blob/fdbefc3d4c2fcb8ae074dd99a2664da35bc55afe/marsbar/%40mardo/mardo.m#L178

I tried directly editing the SPM.mat and changing the "fname" so that it points to the correct directory, however that caused a "Design does not contain images" error.

**Comment by TamerGezici** [comment]
My first level results directory looks like this:

![image](https://user-images.githubusercontent.com/11014942/186446253-595ffed3-027f-4d3e-ac0b-8daec52fc7a2.png)

Smoothened files directory:

![image](https://user-images.githubusercontent.com/11014942/186446645-cfaf8778-7698-4de6-b212-a2bc10467f50.png)

Inside the directory:

![image](https://user-images.githubusercontent.com/11014942/186446742-e2fee0f8-c465-4a42-8bcc-a51a42f329f1.png)

**Comment by matthew-brett** [comment]
Did you run the `marsbar on` command before you started your script?

**Comment by TamerGezici** [comment]
> Did you run the `marsbar on` command before you started your script?

Hi, thanks a lot for your prompt answer. This is actually very urgent -- I need to do this analysis as soon as possible.

I didn't know I needed to do that (or forgot to).



I did that, and I think the script ran, but I saw a warning. The warning is at the bottom, it is trying to save SPM file to the old directory.

```
K>> desfile

desfile =

    'E:\fMRI\fr-pr-3-AA\HCFprep\B_block\studyB_3D\aamod_firstlevel_model_00001\sub-01\stats\SPM.mat'

K>> D
 
D =
 
[mardo_5 design object]
 
SPM working dir    	D:\HCFprep\AAresults\studyB_3D\aamod_firstlevel_model_00001\sub-01\stats
Design type:       	SPM5                                                                    
Modality:          	fmri                                                                    
Has filter?:       	yes                                                                     
Has images?:       	yes                                                                     
MarsBaR estimated?:	no                                                                      
Description:                                                                                
         Basis_functions: hrf                                                               
      Number_of_sessions: 2                                                                 
      Trials_per_session: 12 12                                                             
      Interscan_interval: 2.00 {s}                                                          
        High_pass_Filter: [min] Cutoff: 128 {s}                                             
      Global_calculation: mean voxel value                                                  
      Grand_mean_scaling: session specific                                                  
    Global_normalisation: None                                                              
 
Saving design to file D:\HCFprep\AAresults\studyB_3D\aamod_firstlevel_model_00001\sub-01\stats\SPM.mat
Warning: Error using save
Cannot create 'SPM.mat' because 'D:\HCFprep\AAresults\studyB_3D\aamod_firstlevel_model_00001\sub-01\stats' does
not exist. 
> In mardo_2/save_spm (line 40)
  In roi_3B_sr (line 83) 
```

**Comment by matthew-brett** [comment]
I think you want:

```
save_spm(D, desfile);
```

**Comment by TamerGezici** [comment]
> I think you want:
> 
> ```
> save_spm(D, desfile);
> ```

Thanks. I will try this next time I run the script and re-open the issue if I need help. Have a nice day!
